version: "3.8"

services:
  db:
    image: mysql:8.0
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  web:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./src/public:/var/www/html/public
      - ./src/database/db.php:/var/www/html/database/db.php
      - ./src/database:/var/www/html/database
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      - .env:/var/www/html/.env
    ports:
      - "80:80"
    env_file:
      - .env

volumes:
  db_data: